import { 
    ElAside,
    ElAvatar,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElMain,
    ElSubmenu,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElInfiniteScroll,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElForm,
    ElFormItem,
    ElInput,
    ElButton,
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification
} from 'element-plus'

export const components = [
    ElAside,
    ElAvatar,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElSubmenu,
    ElMain,
    ElForm,
    ElFormItem,
    ElInput,
    ElMenu,
    ElButton,
    ElMenuItem,
    ElMenuItemGroup,
    ElRadio,
    ElRadioButton,
    ElRadioGroup
]
export const plugins = [
    ElInfiniteScroll,
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification
]